### ISSUE TITLE
Event Listners Count always return 0 despite of adding listners

### ISSUE THREAD

**Issue by ghost** [aleclarson/emitter-kit#52] opened 2018-05-01 07:27 UTC
```swift

        signInEvent = Event<MasterViewController>()
        
        //button touchup inside event
        btnSignIn.onTap { [weak self] in
            if self == nil {
                return
            }
            self?.signInEvent?.emit(SigninController()) //Emit data Here
            print(self?.signInEvent?.listenerCount) //Always return 0
        }
      
        //Listner
        let listner = signInEvent?.on({ (data) in
            print(data)
        })
```

**Comment by aleclarson** [comment] 2018-05-01 13:05
Hello! What version of Swift and EmitterKit are you using?

**Comment by aleclarson** [comment] 2018-05-01 13:37
Are you forgetting to retain your `signInEvent` listener?

If so, this is a duplicate of #27. Please confirm. :)

**Closed** 2018-05-11 14:15 UTC
Labels: support
